"""empty message

Revision ID: 8300cc527c9f
Revises: de5b9e57bf60
Create Date: 2021-04-27 17:47:39.955616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8300cc527c9f'
down_revision = 'de5b9e57bf60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('photo_url', sa.String(length=250), nullable=True))
    op.add_column('planets', sa.Column('photo_url', sa.String(length=250), nullable=True))
    op.add_column('starships', sa.Column('photo_url', sa.String(length=250), nullable=True))
    op.add_column('vehicles', sa.Column('photo_url', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'photo_url')
    op.drop_column('starships', 'photo_url')
    op.drop_column('planets', 'photo_url')
    op.drop_column('people', 'photo_url')
    # ### end Alembic commands ###
